### ISSUE TITLE
The keys .7z file requires a password and I can't find it

### ISSUE THREAD

**Issue by JoseBCN84** [Abd-007/Switch-Emulators-Guide#10]
Hi,

I've downloaded the Keys 14.1.2 (UPDATED).7z but when I try to open it, it asks for a password which I cannot find anywhere.

Please help

Thanks

**Comment by dani814** [comment]
try this one it doesnt have password for the archive
[Keys-14.1.2.zip](https://github.com/Abd-007/Switch-Emulators-Guide/files/10475393/Keys-14.1.2.zip)
