### ISSUE TITLE
Link to keys is not longer working

### ISSUE THREAD

**Issue by alvaromanjon** [Abd-007/Switch-Emulators-Guide#22]
[Link](https://pastebin.com/Y5Z9Di5H) to download Switch keys is down on both Yuzu and Ryujinx guides

**Comment by Abd-007** [comment]
Fixed.

**Comment by AhsanSarwar45** [comment]
@Abd-007 Still not working for me.

**Comment by Abd-007** [comment]
Got taken down again, fixed now

**Comment by ARGs-code** [comment]
Appears to be down again. Everything else appears to be working though.

**Comment by aalnext** [comment]
The links got taken down
