### ISSUE TITLE
Skyline

### ISSUE THREAD

**Issue by ggtylerr** [Abd-007/Switch-Emulators-Guide#23]
Even though development has stopped, it'd be nice if there was a guide included for it. (That and the support channel is closed now, and I'm stuck on a black screen with 0 fps no matter what I try, so it'd be nice to have some common troubleshooting guides)

If not, at least something for Strato whenever that becomes production ready.

**Comment by Abd-007** [comment]
Sorry but we have no plans currently to make a skyline/strato guide.

Even when the project was alive, neither did it run well enough nor were we interested in making a guide for it. And the fact that we didn't even have any experience with the emulator also pushed that sentiment. With the project shutting down, any and all motivation has died now.

If strato goes on to become a successful and working android switch emulator, then maybe we'll make a guide for it. But for now, there's just no interest to bother making a guide

**Comment by ggtylerr** [comment]
Understandable, I hope there is one in the future since it's basically the only way to emulate on an Android. There's a lot of people (myself included) that would love a proper guide :)
