### ISSUE TITLE
broken key links

### ISSUE THREAD

**Issue by Bco1981** [Abd-007/Switch-Emulators-Guide#24]
I have been trying a few days now and at different hours but none of the key links seems to work.
tried with both brave and Chrome browsers.

**Comment by marios-codes** [comment]
I have the same problem. The files have been removed. Can they be updated?

**Comment by Bco1981** [comment]
> I have the same problem. The files have been removed. Can they be updated?

well it wasn't that hard to google yuzu prod keys and find it.
