### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by steel101** [Abd-007/Switch-Emulators-Guide#31]
aHR0cHM6Ly9naXRodWIuY29tL3N0ZWVsMTAxL1N3aXRjaC1FbXVsYXRvcnMtR3VpZGUvYmxvYi9tYWluL0xpbmtzLm1k

If you know what this is then your welcome use it as you need.

**Comment by steel101** [comment]
New link with all links working now

**Comment by steel101** [comment]
You added links back again

**Comment by Abd-007** [comment]
Yeah I did

**Comment by steel101** [comment]
Why you add them back you not worried about Nintendo they have tried 3 times to shut down my forks of projects
